[package]
name = "foundry"
version = "0.4.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anymap = "0.12.1"
paste = "1.0.11" # snake case for comp iterator
foundry-macro = {path = "deps/foundry-macro"}